import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import AuthProvider from "./components/AuthProvider";
import HeartbeatProvider from "./components/HeartbeatProvider";
import Navbar from "./components/Navbar";
import SocketProvider from "./components/SocketProvider";
import "./globals.css";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} antialiased`}>
        <div className="flex flex-col min-h-screen">
          <AuthProvider>
            <HeartbeatProvider>
              <SocketProvider>
                <Navbar />
                {/* Let children take up remaining space */}
                <main>{children}</main>
              </SocketProvider>
            </HeartbeatProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
