import NotificationProvider from "@/lib/NotificationProvider";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import AuthProvider from "../lib/auth/AuthProvider";
import SocketProvider from "../lib/socket/SocketProvider";
import CallPopupProvider from "./components/Chats/Chatbox/CallPopupProvider";
import Navbar from "./components/Navbar";
import "./globals.css";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} antialiased`}>
        <div className="flex flex-col min-h-screen">
          <AuthProvider>
            <SocketProvider>
              <CallPopupProvider>
                <NotificationProvider>
                  <main>
                    <Navbar />
                    {children}
                  </main>
                </NotificationProvider>
              </CallPopupProvider>
            </SocketProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
