"use client";

import { useState } from "react";
import ReactMarkdown from "react-markdown";
import ModalBase from "../Popup/ModalBase";

const TermsAndConditions = ({ readOnly = false }: { readOnly?: boolean }) => {
  const [showModal, setShowModal] = useState(false);

  return (
    <>
      <div className="flex flex-row gap-2 items-center justify-center">
        <input
          name="termsAndConditions"
          type="checkbox"
          required
          className="disabled:opacity-100 checkbox checkbox-ghost checkbox-primary rounded"
          defaultChecked={readOnly}
          disabled={readOnly}
        />
        <div className="flex flex-col text-base-content">
          I agree with the Terms & Conditions of Safehub{" "}
          <span className="text-sm text-base-content/70">
            Read our terms & conditions{" "}
            <span
              className="text-primary cursor-pointer"
              onClick={() => setShowModal(true)}
            >
              here...
            </span>
          </span>
        </div>
      </div>

      {showModal && (
        <TermsAndConditionsModal onClose={() => setShowModal(false)} />
      )}
    </>
  );
};

const TermsAndConditionsModal = ({ onClose }: { onClose?: () => void }) => {
  return (
    <ModalBase onClose={onClose}>
      <div className="bg-white p-4 rounded shadow-md text-base-content">
        <div className="flex flex-col max-w-200 min-h-0 max-h-150 overflow-y-auto py-2">
          <div className={`prose max-w-none text-base-content`}>
            <ReactMarkdown>
              {`# SafeHub – Terms and Conditions

Welcome to SafeHub. By accessing or using this platform, you agree to the following Terms and Conditions.

---

## 1. Purpose

SafeHub is an AI-powered platform designed to provide general mental health information, educational resources, and links to social welfare support services.  
**SafeHub does not provide medical advice, diagnosis, therapy, counseling, or emergency intervention.**

---

## 2. Not for Emergencies

SafeHub is **not** an emergency or crisis-response service.  
If you are in immediate danger, experiencing a mental health crisis, or need urgent assistance, please contact:

- Local emergency services  
- A licensed mental health professional  
- National or community crisis hotlines

---

## 3. AI-Generated Content

Information on SafeHub is generated by artificial intelligence and may be **inaccurate, incomplete, or outdated**.

Users should:

- Independently verify important information  
- Seek professional help for medical, psychological, or legal concerns  

SafeHub is not responsible for decisions made based on AI-generated content.

---

## 4. User Responsibilities

By using SafeHub, users agree to:

- Use the platform **legally, responsibly, and respectfully**  
- Avoid posting harmful, abusive, discriminatory, or misleading content  
- Protect their login credentials and personal information (if applicable)

Misuse of the platform may result in restricted or revoked access.

---

## 5. Privacy

SafeHub may collect limited user data to improve platform functionality and services.  
We do **not** sell personal information.

For full details on data collection, usage, and protection, please refer to the **Privacy Policy**.

---

## 6. Third-Party Links

SafeHub may include links to external websites, organizations, or services.  
These are provided for convenience and informational purposes only.

SafeHub does **not** endorse or control third-party content and is not responsible for:

- External site accuracy  
- Their policies or practices  
- Any actions taken by third-party services

---

## 7. Limitation of Liability

SafeHub is not liable for:

- Errors or omissions in AI-generated content  
- Emotional distress or harm resulting from platform use  
- Decisions or actions taken based on provided information  
- Technical issues, outages, or interruptions

Use of the platform is at your own risk.

---

## 8. Changes to Terms

SafeHub may update these Terms and Conditions at any time.  
Continued use of the platform constitutes acceptance of the updated terms.

---
`}
            </ReactMarkdown>
          </div>
        </div>
        <div className="flex flex-row justify-end">
          <button onClick={onClose} className="btn mt-2">
            Close
          </button>
        </div>
      </div>
    </ModalBase>
  );
};

export default TermsAndConditions;
